FormAcc/urls.py
from django.urls import path
from . import views

app_name="calculator"
urlpatterns=[
    path("", views.FormCalc,name="FormCalc")
]

duelcalc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("FormAcc.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "FormAcc.views.page_404_not_found"
handler500= "FormAcc.views.page_500_error_server"

FormAcc/models.py
from django.db import models

# Create your models here.

FormAcc/views.py
from django.shortcuts import render
from django.views.defaults import page_not_found,server_error


import math

# Create your views here.
totalAccount = 0
def FormCalc(request):
    form = {}
    global totalAccount
    totalAccount = 0
    if request.method=="POST":
        form = request.POST
        form = form.dict()     
        form["PriceGems"] = priceGems(form["gems"]) if form["gems"] else "0.0$"
        form["PriceCards"] = priceCards(form["URcards"],form["SRcards"]) \
            if form["URcards"] or form["SRcards"] else "0.0$"

        phases = [form["PhaseDM"],form["PhaseDSOD"],form["PhaseGX"],\
            form["PhaseDS"],form["PhaseZexal"]]

        form["PricePhases"] = pricePhases(phases)

        i=35
        characterLvl=[]
        while i>=10 :
            characterLvl.append(form["Cha"+str(i)])
            i-=5
        form["PriceChar"] = priceCharacters(characterLvl)

        tickets = [form["ticketsUR"],form["ticketsURDream"],form["ticketsSR"],\
            form["ticketsSRDream"],form["ticketsSU"],form["ticketsR"],\
                form["ticketsN"],form["ticketsSkill"]]

        form["PriceTickets"] = priceTickets(tickets)
        form["total"] = f"{round(totalAccount,2)}$"
    return render(request,"form/index.html",form)

def page_404_not_found(request,exception):
    return page_not_found(request,exception,template_name="error/404.html")

def page_500_error_server(request):
    return server_error(request,template_name="error/500.html")

def priceGems(gems):
    gems=int(gems)
    gems = gems*math.exp((gems/(gems+1)))/3000 
    gems= round(gems,2)

    global totalAccount
    totalAccount += gems
    return f"{gems}$"

def priceCards(ur,sr):
    ur = int(ur) if ur else 0
    sr = int(sr) if sr else 0
    ur = (0.1*math.exp(ur/(ur+1)))*ur/3
    sr = sr/15
    cards = ur + sr
    cards = round(cards,2)

    global totalAccount
    totalAccount += cards
    return f"{cards}$"

def pricePhases (phases):
    total = 0
    for world in phases:
        world = int(world) if world else 0
        total += world/15
    total = round(total,2)

    global totalAccount
    totalAccount += total
    return f"{total}$"

def priceCharacters (char):
    i = 0
    total = 0
    for c in char:
        char[i] = int(c) if c else 0
        i += 1
    char[0]*=1.5  
    char[2]/=1.5
    char[3]/=4
    char[4]/=7
    char[5]/=10
    for c in char:  
        total += c
    total =round(total,2)

    global totalAccount
    totalAccount += total
    return f"{total}$"

def priceTickets (tickets):
    i = 0
    total = 0
    for ticket in tickets:
        tickets[i] = int(ticket) if ticket else 0
        i += 1
    tickets[0] /= 4
    tickets[2] /=10
    tickets[4] /=2
    tickets[5] /= 20
    tickets[6] /= 25
    for ticket in tickets:
        total += ticket
    total = round(total,2)

    global totalAccount
    totalAccount += total
    return f"{total}$"

FormAcc/templates/form/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Calculator to have an approximate 
      value of the value of a starter account of the game yugioh duel links"
    />
    <meta name="distribution" content="global" />
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/favicon.ico' %}"/>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/style.css' %}"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'icons/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'icons/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'icons/favicon-16x16.png' %}"
    />
    <link rel="manifest" href="{% static 'icons/site.webmanifest' %}" />
    <link
      rel="mask-icon"
      href="{% static 'icons/safari-pinned-tab.svg' %}"
      color="#5bbad5"
    />
    <meta name="msapplication-TileColor" content="#00172D" />
    <meta name="msapplication-config" content="{% static 'icons/browserconfig.xml' %}" />
    <meta name="msapplication-square150x150logo" content="{% static 'icons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#00172D" />
    <script src="{% static 'function/index.js' %}"></script>
    <title>Calculator || Calculator of Greed</title>
  </head>
  <body>
    <article class="container">
      <header class="title">
        <h1>Calculator for DuelLinks Account</h1>
      </header>
      <form class="form" method="POST" action="{% url 'calculator:FormCalc' %}">
        {% csrf_token %} {% if total %}
        <fieldset>
          <legend>Price for Account {{total}}</legend>
        </fieldset>
        {% endif %}
        <fieldset>
          <legend>Price for Amount of Gems: {{PriceGems}}</legend>
          <label>
            Amount of Gems
            <input
              id="gems"
              type="number"
              name="gems"
              value="{{gems}}"
              placeholder="Gems"
            />
          </label>
        </fieldset>

        <fieldset>
          <legend>
            Price for Amount of Hight Rarity Cards: {{ PriceCards }}
          </legend>
          <label>
            Amount of UR Cards
            <input
              type="number"
              name="URcards"
              value="{{URcards}}"
              placeholder="UR Cards"
            />
          </label>
          <label>
            Amount of SR Cards
            <input
              type="number"
              name="SRcards"
              value="{{SRcards}}"
              placeholder="SR Cards"
            />
          </label>
        </fieldset>

        <fieldset>
          <legend>Price for Phases´s Levels: {{ PricePhases }}</legend>
          <label>
            Phase in Duel Monster
            <input
              type="number"
              name="PhaseDM"
              value="{{PhaseDM}}"
              placeholder="Phase DM"
            />
          </label>
          <label>
            Phase in Dark Side of Dimensions
            <input
              type="number"
              name="PhaseDSOD"
              value="{{PhaseDSOD}}"
              placeholder="Phase DSOD"
            />
          </label>
          <label>
            Phase in GX Word
            <input
              type="number"
              name="PhaseGX"
              value="{{PhaseGX}}"
              placeholder="Phase GX"
            />
          </label>
          <label>
            Phase in 5D´s word
            <input
              type="number"
              name="PhaseDS"
              value="{{PhaseDS}}"
              placeholder="Phase 5D´s"
            />
          </label>
          <label>
            Phase in ZEXAL WORD
            <input
              type="number"
              name="PhaseZexal"
              value="{{PhaseZexal}}"
              placeholder="Phase ZEXAL"
            />
          </label>
        </fieldset>

        <fieldset>
          <legend>Price for Characters´s Levels: {{ PriceChar }}</legend>
          <label>
            Level > 35
            <input
              type="number"
              name="Cha35"
              value="{{Cha35}}"
              placeholder="35 or more"
            />
          </label>
          <label>
            Level > 30
            <input
              type="number"
              name="Cha30"
              value="{{Cha30}}"
              placeholder="30 - 34"
            />
          </label>
          <label>
            Level > 25
            <input
              type="number"
              name="Cha25"
              value="{{Cha25}}"
              placeholder="25 - 29"
            />
          </label>
          <label>
            Level > 20
            <input
              type="number"
              name="Cha20"
              value="{{Cha20}}"
              placeholder="20 - 24"
            />
          </label>
          <label>
            Level > 15
            <input
              type="number"
              name="Cha15"
              value="{{Cha15}}"
              placeholder="15 - 19"
            />
          </label>
          <label>
            Level > 10
            <input
              type="number"
              name="Cha10"
              value="{{Cha10}}"
              placeholder="10 - 14"
            />
          </label>
        </fieldset>

        <fieldset>
          <legend>Price for Amount of Tickets: {{ PriceTickets }}</legend>
          <label>
            UR Tickets
            <input
              type="number"
              name="ticketsUR"
              value="{{ticketsUR}}"
              placeholder="UR"
            />
          </label>
          <label>
            UR Dream Tickets
            <input
              type="number"
              name="ticketsURDream"
              value="{{ticketsURDream}}"
              placeholder="UR Dream"
            />
          </label>
          <label>
            SR Tickets
            <input
              type="number"
              name="ticketsSR"
              value="{{ticketsSR}}"
              placeholder="SR"
            />
          </label>
          <label>
            SR Dream Tickets
            <input
              type="number"
              name="ticketsSRDream"
              value="{{ticketsSRDream}}"
              placeholder="SR Dream"
            />
          </label>
          <label>
            S/U Tickets
            <input
              type="number"
              name="ticketsSU"
              value="{{ticketsSU}}"
              placeholder="S/U"
            />
          </label>
          <label>
            R Tickets
            <input
              type="number"
              name="ticketsR"
              value="{{ticketsR}}"
              placeholder="R"
            />
          </label>
          <label>
            N Tickets
            <input
              type="number"
              name="ticketsN"
              value="{{ticketsN}}"
              placeholder="N"
            />
          </label>
          <label>
            Skill Tickets
            <input
              type="number"
              name="ticketsSkill"
              value="{{ticketsSkill}}"
              placeholder="Skill"
            />
          </label>
        </fieldset>
        <div class="btnContainer">
          <input
            class="btn btnRestore"
            type="reset"
            value="Restore"
            onclick="restore()"
          />
          <input class="btn btnCalculate" type="submit" value="Calculate" />
        </div>
      </form>
    </article>
  </body>
</html>